import AvatarGenerator from "avatar-generator"
import path from "path"

export const firstAvatarGenerator = async (req) => {
    try {
        const avatar = new AvatarGenerator({
            //All settings are optional.
            parts: ['background', 'face', 'clothes', 'head', 'hair', 'eye', 'mouth'], //order in which sprites should be combined
            partsLocation: path.join(__dirname, '../node_modules/avatar-generator/img'), // path to sprites
            imageExtension: '.png' // sprite file extension
        })
        const variant = "male" // By default 'male' and 'female' supported
        const image = await avatar.generate(req.body.email, variant)
        image
            .resize(300, 300)
            .png()
            .toFile('tmp/autoGeneratedAvatar300x300.png')
        const avatarPath = image.options.fileOut
        req.user = { avatarPath }
    } catch (e) { console.log(e) }
}